config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out', to: "devise/sessions#destroy", as: "sign_out"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  resources :domains
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
  has_many :visits
  belongs_to :user

  validates :user, :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :domains

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness:true

end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :domain
  belongs_to :visitor

  validates :domain, :visitor, :url, :browser, :new_visit, presence:true

end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :visits

  validates :ip_address, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end


  private

  def require_login
    unless current_user
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_user_registration_path
    end
  end

end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController

  before_action :require_login
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  def index
    @domains = current_user.domains
  end

  def show
  end

  def new
    @domain = Domain.new
  end

  def edit
  end

  def create
    @domain = Domain.new(user:current_user)
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_domain
    @domain = Domain.find(params[:id])
  end

  def domain_params
    params.require(:domain).permit(:name, :user_id,)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :require_login

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h2>Edit Domain</h2>
<%= render 'form' %>

app/views/domains/index.html.erb
<h2>Your Domains</h2>
<ul>
  <% @domains.each do |domain| %>
  <li><%= link_to domain.name, domain_path(domain) %></li>
  <% end %>
</ul>

app/views/domains/new.html.erb
<h2>Add New Domain</h2>
<%= render 'form' %>

app/views/domains/show.html.erb
<h2><%= @domain.name %></h2>

Charts, data, metrics to follow.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whad</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <h1><%= link_to "Welcome to Whad-R-ULookin'-At?", root_path %></h1>
  <nav>
    <%= link_to "Log Out", sign_out_path %>
  </nav>
  <%= yield %>
</body>
</html>

app/views/welcome/index.html.erb
<h2>Available Options</h2>
<ul>
  <li><%= link_to "Add Domain", new_domain_path %></li>
  <li><%= link_to "View Domains", domains_path %></li>
</ul>